export const MAX_LENGTH_TEXT_AREA = 500;
export const MAX_LENGTH_TEXT = 500;
export const DURATION_TIMEOUT_SECONDS = 5;
export enum NAME_ACTION {
  //category
  CREATE_CATEGORY = 'CREATE_CATEGORY',
  DEFAULT_CATEGORY = 'CREATE_CATEGORY',
  REMOVE_CATEGORY = 'REMOVE_CATEGORY',
  UPDATE_CATEGORY = 'UPDATE_CATEGORY',
  GET_CATEGORY = 'GET_CATEGORY',

  //product
  CREATE_PRODUCT = 'CREATE_PRODUCT',
  DEFAULT_PRODUCT = 'CREATE_PRODUCT',
  REMOVE_PRODUCT = 'REMOVE_PRODUCT',
  UPDATE_PRODUCT = 'UPDATE_PRODUCT',
  GET_PRODUCT = 'GET_PRODUCT',

  //order
  CREATE_ORDER = 'CREATE_ORDER',
  DEFAULT_ORDER = 'CREATE_ORDER',
  REMOVE_ORDER = 'REMOVE_ORDER',
  UPDATE_ORDER = 'UPDATE_ORDER',
  GET_ORDER = 'GET_ORDER',

  //image
  CREATE_IMAGE = 'CREATE_IMAGE',
  DEFAULT_IMAGE = 'CREATE_IMAGE',
  REMOVE_IMAGE = 'REMOVE_IMAGE',
  UPDATE_IMAGE = 'UPDATE_IMAGE',
  GET_IMAGE = 'GET_IMAGE',
}
